# Generated by Django 4.1.3 on 2022-11-10 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0002_potfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='potfolio',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
