# Generated by Django 4.1.3 on 2022-11-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0003_potfolio_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='potfolio',
            new_name='Portfolio',
        ),
    ]
