# Generated by Django 4.1.3 on 2022-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0005_alter_portfolio_price_alter_portfolio_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('asset_name', models.CharField(max_length=64)),
                ('asset_id', models.CharField(max_length=64)),
                ('asset_symbol', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=280)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
    ]
