# Generated by Django 4.1.3 on 2022-11-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='potfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('asset_name', models.CharField(max_length=64)),
                ('asset_id', models.CharField(max_length=64)),
                ('asset_symbol', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_spent', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
