# Generated by Django 4.1.3 on 2022-11-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0004_rename_potfolio_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
