# Generated by Django 4.1.3 on 2022-11-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinscreener', '0006_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='asset_symbol',
        ),
    ]
